CREATE DATABASE IF NOT EXISTS faq_app CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'faq_user'@'%' IDENTIFIED BY 'neo';
GRANT ALL PRIVILEGES ON faq_app.* TO 'faq_user'@'%';
FLUSH PRIVILEGES;
